"""add score dimensions and flag metadata

Revision ID: 557af086b099
Revises: 569ddfcc8fff
Create Date: 2026-07-05 11:33:05.563346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557af086b099'
down_revision: Union[str, Sequence[str], None] = '569ddfcc8fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "flags",
        sa.Column(
            "severity",
            sa.String(length=20),
            nullable=False,
            server_default="medium",
        ),
    )

    op.add_column(
        "flags",
        sa.Column(
            "timestamp_in_call",
            sa.String(length=20),
            nullable=False,
            server_default="00:00:00",
        ),
    )

    op.add_column(
        "scores",
        sa.Column(
            "needs_discovery",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )

    op.add_column(
        "scores",
        sa.Column(
            "product_knowledge",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )

    op.add_column(
        "scores",
        sa.Column(
            "objection_handling",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )

    op.add_column(
        "scores",
        sa.Column(
            "compliance",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )

    op.add_column(
        "scores",
        sa.Column(
            "next_step_booking",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )

    op.alter_column("flags", "severity", server_default=None)
    op.alter_column("flags", "timestamp_in_call", server_default=None)

    op.alter_column("scores", "needs_discovery", server_default=None)
    op.alter_column("scores", "product_knowledge", server_default=None)
    op.alter_column("scores", "objection_handling", server_default=None)
    op.alter_column("scores", "compliance", server_default=None)
    op.alter_column("scores", "next_step_booking", server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'next_step_booking')
    op.drop_column('scores', 'compliance')
    op.drop_column('scores', 'objection_handling')
    op.drop_column('scores', 'product_knowledge')
    op.drop_column('scores', 'needs_discovery')
    op.drop_column('flags', 'timestamp_in_call')
    op.drop_column('flags', 'severity')
    # ### end Alembic commands ###
