"""add transcript segments

Revision ID: 569ddfcc8fff
Revises: ff324f8735b1
Create Date: 2026-07-05 10:26:00.085344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569ddfcc8fff'
down_revision: Union[str, Sequence[str], None] = 'ff324f8735b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_id'), 'transcript_segments', ['id'], unique=False)
    op.add_column('transcripts', sa.Column('full_text', sa.Text(), nullable=False))
    op.add_column('transcripts', sa.Column('language', sa.String(length=20), nullable=False))
    op.add_column('transcripts', sa.Column('duration_seconds', sa.Float(), nullable=False))
    op.add_column('transcripts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('transcripts', 'transcript')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('transcripts', 'created_at')
    op.drop_column('transcripts', 'duration_seconds')
    op.drop_column('transcripts', 'language')
    op.drop_column('transcripts', 'full_text')
    op.drop_index(op.f('ix_transcript_segments_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    # ### end Alembic commands ###
