"""update call table

Revision ID: ff324f8735b1
Revises: cb59cf996568
Create Date: 2026-07-05 10:10:53.108423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff324f8735b1'
down_revision: Union[str, Sequence[str], None] = 'cb59cf996568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('calls', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.add_column('calls', sa.Column('file_type', sa.String(length=20), nullable=False))
    op.add_column('calls', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('calls', 'advisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('calls', 'audio_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('audio_file', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.alter_column('calls', 'advisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('calls', 'created_at')
    op.drop_column('calls', 'file_type')
    op.drop_column('calls', 'file_path')
    op.drop_column('calls', 'file_name')
    # ### end Alembic commands ###
